In [4]:
import torch

ModuleNotFoundError: No module named 'torch'

# Torch Tensor
텐서 생성

In [ ]:
# 0으로 채운 Tensor
zero_tensor = torch.zeros(3, 3)
print(zero_tensor)

# 1로 채운 Tensor
ones_tensor = torch.ones(3, 3)
print(ones_tensor)

# 랜덤한 값으로 채운 Tensor
random_tensor = torch.rand(3, 3)
print(random_tensor)

# 특정 값을 갖는 Tensor
float_tensor = torch.full((3, 3), -0.7)
print(float_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4874, 0.2845, 0.9682],
        [0.2748, 0.6645, 0.9868],
        [0.8271, 0.8414, 0.6713]])
tensor([[-0.7000, -0.7000, -0.7000],
        [-0.7000, -0.7000, -0.7000],
        [-0.7000, -0.7000, -0.7000]])


텐서 인덱싱

In [ ]:
list_eliment = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
list_eliment[1][1]

5

In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor[1, 1])

tensor(5)


In [ ]:
print(tensor[:, 1])

tensor([2, 5, 8])


텐서 연산

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# 덧셈
add_result = x + y
print("Addition Result:", add_result)

# 뺄셈
sub_result = x - y
print("Subtraction Result:", sub_result)

# 곱셈 (element-wise)
mul_result = x * y
print("Multiplication Result:", mul_result)

# 나눗셈 (element-wise)
div_result = x / y
print("Division Result:", div_result)

Addition Result: tensor([5, 7, 9])
Subtraction Result: tensor([-3, -3, -3])
Multiplication Result: tensor([ 4, 10, 18])
Division Result: tensor([0.2500, 0.4000, 0.5000])


In [ ]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# 행렬곱
matmul_result = torch.matmul(a, b)
print(matmul_result)

# 전치 행렬
transpose_result = a.T
print(transpose_result)

tensor([[19, 22],
        [43, 50]])
tensor([[1, 3],
        [2, 4]])


In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

try:
    dot_product = torch.dot(a, b)
    print(dot_product)
except RuntimeError as e:
    print("Error:", e)

tensor(32)


브로드캐스팅

In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])

print(A + 2)

[[3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

print(np.matmul(A, B))

[[ 58  64]
 [139 154]]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

try:
    matmul_result = np.matmul(A, B)
    print(matmul_result)
except ValueError as e:
    print("Error:", e)

Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


In [ ]:
a = torch.tensor([[0, 0], [0, 0]]) # (2, 2)
b = torch.tensor([1, 2]) # (2,) -> (2,2)로 늘려서 연산
c = torch.tensor([[1], [2]]) # (1, 2) -> (2,2)로 늘려서 연산

print(a + b)
print(a + c)

tensor([[1, 2],
        [1, 2]])
tensor([[1, 1],
        [2, 2]])


In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]]) # (2, 3)
b = torch.tensor([10, 20, 30]) # (3,) -> (2, 3)으로 확장

print(a * b)

tensor([[ 10,  40,  90],
        [ 40, 100, 180]])


In [ ]:
import torch

A = torch.ones(2, 2, 2) # (2, 2, 2)
B = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32) # (2, 2) -> (2, 2, 2)로 확장됨

print(A)
print(torch.matmul(A, B))

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[[4., 6.],
         [4., 6.]],

        [[4., 6.],
         [4., 6.]]])


In [ ]:
a = torch.tensor([[1, 2], [3, 4]]) # (2, 2)
b = torch.tensor([1, 2, 3]) # (3,)

try:
    print(a + b)
except RuntimeError as e:
    print("Error:", e)

Error: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1


In [ ]:
A = torch.ones(2, 2)  # Shape: (2, 2)
B = torch.tensor([1, 2], dtype=torch.float32)  # Shape: (2,)

print(torch.matmul(A, B))

tensor([3., 3.])
